---
title: Murilo Zangari
logo: "/images/2024-04-21 17_57_44.934-0300.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
 PhD in Computer Science | Data Scientist  
  <br><br>
  [View My LinkedIn Profile](https://www.linkedin.com/in/murilozangari/)
   <br><br>
  [View my Kaggle Profile](https://www.kaggle.com/murilozangari/)
   <br><br>
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
---
