---
title: Murilo Zangari
logo: "/images/2024-04-21 17_57_44.934-0300.jpg?raw=true" # your photo (or logo) here
description: | # your text below (remove <br> elements if you don't need line breaks)
  PhD in Computer Science | Analytics | Data Scientist  
   
  With twelve years of experience in transforming raw data into actionable insights and developing advanced machine learning models, I bring a robust set of skills grounded in computer science, programming languages, mathematics, and statistics. Currently, I am fully committed to enhancing my skills through prestigious data science courses and hands-on projects for my portfolio 
   
  [View My LinkedIn Profile](https://www.linkedin.com/in/murilozangari/)
   
  [View my Kaggle Profile](https://www.kaggle.com/murilozangari/)
   
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
---
