---
title: Murilo Zangari
description: "PhD in Computer Science | Analytics | Data Scientist"
logo: "/images/2024-04-21 17_57_44.934-0300.jpg?raw=true"
---
  <a href="https://www.linkedin.com/in/murilozangari/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.kaggle.com/murilozangari/"> View my Kaggle Profile</a>
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

