title: Murilo Zangari
logo: "/images/2024-04-21 18_18_08.378-0300.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD in Computer Science 
  <br>
  Data Scientist 
  <br>
  <a href="https://www.linkedin.com/in/murilozangari/" target="_blank">LinkedIn Profile</a> 
  <br>
  <a href="https://www.kaggle.com/murilozangari/" target="_blank">Kaggle Profile</a> 
  <br>
  murilo.zangari@gmail.com
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
